Follow unfollow
foodbank-ymg/thanks-web-backend pull request #10
Opened 2023-01-27 14:51 UTC by Nekodigi

Follow unfollowの基本動作を実装しました。
ステートを日本語にするのか、テキストメッセージをコードに埋め込むのか等いくつか改善が考えられる個所もあります。
プログラムの構造について、改善案があれば指摘お願いします。

2023-01-30 09:56 UTC, tetsuyanh requested changes
たくさん指摘しました。
良い設計になりそうと納得してもらえる部分、修正お願いします。

2023-01-30 09:56 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +    )
Promise.allだけど基本1つずつのみ送信する仕様にしたいと考えています。
（events[0]しか対応しない←検討したいのですぐ実装しなくていいです）

LINEから画像を複数枚送信したら、複数入ってきそう。
理由は、複数受けて一部が成功して一部が失敗したというケースに対処したくない（IFが複雑になる）、です。

で、`catch`でエラーを補足して、このようにしたいですがどうでしょう？
- エラー内容をまんまエラーログに吐く（GCPで動かすのでCloudLoggingに集約される）
- ユーザー向けには定型のエラーメッセージ「システムでエラーが発生しました。」を返す

ちなみに、テキスト入力を期待してるのに、画像を送信してきたら、
それはエラーではなく、再度「〇〇を入力してください」と返答して正常系として扱います。

2023-01-30 09:56 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +    )
unfollow時は空resolve（null応答かな）してますよね。

unfollowされた後は、LINEの返答ができなくなっています。
resultのnullチェックして中身がある時のみ、 `res.json()` しましょう。

2023-01-30 09:56 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +  updateManager(manager)
followとmessageの処理それぞれをこの段階でifで切り分け、その応答専用の関数を呼び分け、
unfollowのように早期リターンすると良いと思いました。
いずれ、postbackイベントも入ってきます。
（早期リターンご存じですかね？知らなければググってみてください）

早期リターンを抜けて到達したイベントは、未対応イベントとみなせます。

2023-01-30 09:56 UTC, tetsuyanh commented on src/lib/firestore/manager.ts
> +  const manager = (await db.collection('managers').doc(lineId).get()).data()
レノファPJの方で、FireStoreとJSのConverterを仕込んでます。
参考にしてください。

https://github.com/digitech-ymg/renofa-parking-web/blob/main/cmd/src/firestore.ts#L48-L91

2023-01-30 09:56 UTC, tetsuyanh commented on src/types/managers.d.ts
> +  createdAt: firestore.Timestamp
別指摘のConverterを使えば、
Firestoreのtimestamp型を蔓延させずに、JSのDate型とできるはずです。
DBをFirestoreに依存させ過ぎないようにしておきます。

2023-01-30 09:56 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +    if (manager.name === '' || manager.status === '名前入力') return newManager
stautsはすべて定数にして、`constants.ts`とかに集約したいです。

初期ステータスも定義決めましょう。
`default`や`none`など。

2023-01-30 09:56 UTC, tetsuyanh commented on src/lib/line/template.ts
> +export const ConfirmTemplate = (text: string, alt: string) => {
テキスト返答もよく使うので共通化しちゃいましょう。
`export const TextTemplate = (text: string) {
  ...
}`

2023-01-30 09:56 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +  updateManager(manager)
ここで集約してupdateManagerを呼ぶのは抵抗があるというか、エラーチェックもせずメッセージを返してしまいます。。
個別の関数の中で必要な時に都度やりませんか？

2023-01-30 09:56 UTC, tetsuyanh commented on src/handler/manager_line/setup.ts
> +} from '@line/bot-sdk'
未使用のimportがいくつかあって、厳密にやるならLinterで警告できますが、
開発初期は割と邪魔ですかね。無視してもらっても大丈夫です。

2023-01-30 09:56 UTC, tetsuyanh commented on src/handler/manager_line/setup.ts
> +  manager.enable = true
`名前決定`と題した関数名の中で、他で更新されることを期待して参照引数の中身を弄るのは忌避していきましょう。
（想定していない/しずらい「副作用」とよく言われます）
強引なupdateManager集約はやめようという指摘と通づるところです。

この関数の呼び元がこの関数の前にパラメータ更新するのがいいです。

2023-01-30 09:56 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +  updateManager(manager)
reactが複数のactionとmessageですが、複数を前提にしてはどうでしょうか？

このように組み合わせて、個別メッセージを再利用して数をできる限り抑えようかと。
LINEの吹き出しも複数になる感じです。（ReplyTokenで返すので全て無料のはず）

初回フォロー時（名前未設定）
- tellWelcome
- askName

フォロー再開時
- tellWelcomeBack

名前聞いてるのに画像送ってきた（askNameAgainとか別に作らない）
- askName

2023-01-30 09:56 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +  const manager = await getManagerByLineId(event.source.userId)
getの中で不在なら作るまでやらずに、
getした結果nullなら、`manager = createManager(event.source.userId)`を呼ぶように分けたいです。

2023-01-30 09:56 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +  updateManager(manager)
`react`はPromise<Message[]>を返すのどうですかね？
（関数を返さずに、整形済み応答メッセージ配列）
これが最後に成功して、thenの結果をreplyする。

個別の関数はDB操作などもあるため、途中でエラーが発生したらrejectを返して最上位でcatchする。

DB更新がない処理（適当でイメージです）
```
return [tellWelcomeBack()]
```

DB更新が必要な処理（適当でイメージです）
```
return updateManageer().then(() => {
  return [TextTemplate("ようこそ"), askName()]
})
```

2023-02-04 01:53 UTC, Nekodigi commented
コンバーター、ステータス管理という指摘していただいた部分を書き換えました。
指摘の中で、一部分からない部分があったので、その部分は推測して修正しました。
レビューお願いします。

2023-02-06 05:50 UTC, tetsuyanh commented on src/handler/manager_line/setup.ts
> +} from '@line/bot-sdk'
動作には影響せず、まだ設計が流動的なので保留でOK。

2023-02-06 05:56 UTC, tetsuyanh commented
@Nekodigi 
> 指摘の中で、一部分からない部分があったので、その部分は推測して修正しました。

ここはどこでしょうか？
あと、そもそもPRのコメントにReplyする形で聞いてください。
一点だけの確認であれば、私もなる早で回答できます。
推測が違えば、上津原くんの時間が全く無駄になってしまいます。。

2023-02-06 07:29 UTC, tetsuyanh requested changes
お待たせしました。指摘入れました。

2023-02-06 07:29 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +          ),
・ここもreplyMessageで済むはずです。（pushMessageを使う理由あれば回答ください）
・`event[0]`ではなく、mapで展開している個別の`event.source.userId`が良いはずです。

2023-02-06 07:29 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +        console.log(err)
`console.error`の方を使ってはどうでしょうか？
（ロギングにエラーレベルが渡るかちょっと覚えてませんが。。）

2023-02-06 07:29 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +        if (result !== null) res.json(result)
JSの広義のfalsy判定を使ってもいい気がしました。
nullもundefinedも""（空文字）も全て、Falsyな値は返さない。
`if (!result) {`

2023-02-06 07:29 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +      .then((result) => {
改めてこういう形を提案します。どうでしょう？

私もSDKのサンプルを雛形にしてみました。
https://github.com/line/line-bot-sdk-nodejs/blob/next/examples/echo-bot-ts/index.ts#L62-L92

```
const results = await Promise.all(
  events.map(async (event: WebhookEvent) => {
    // handleEventが必要なDB処理などを実行しユーザー返答Message配列のPromiseを返してくる。
    // this.clientは渡さなくてよくなる
    const messages = await handleEvent(event).catch((err) => {
      if (err instanceof Error) {
        console.error(err);
        // LINEでエラーの旨を伝えたいので一旦コメントアウト
        // return res.status(500).json({
        // status: 'error',
        //});
        // 異常時は定型メッセージで応答
        return client.replyMessage(event.replyToken, [{定型}])
      })
    })

    // 正常時にそのメッセジーを返し、結果をmapに集約する
    return client.replyMessage(event.replyToken, [tellWelcome(event), askName()])
  })
);

// すべてが終わり、resultsをBodyとしてhttpの200を返してる
return res.status(200).json({
  status: 'success',
  results,
});
```

2023-02-06 07:29 UTC, tetsuyanh commented on src/handler/manager_line/setup.ts
> +}
この層は、必要なパラメータを直接受け取りメッセージを整形するだけにした方がよくないですかね？
（前にも言いましたが、LINEのSDKの仕様`event.message.type`がここまで広がってしまうことになっています）
どんなケースで使われる/使われない、をここで管理すべきではないと考えています。
validationをやるなら、上位で済ませるべきかなと。
他の場所も同様です。

```suggestion
export const confirmName = (name: string) => {
  return ConfirmTemplate(`お名前は${name}でよろしいですか？`, '名前確認')
}
```

2023-02-06 07:29 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +      manager.enable = true
manager.enable = trueの後に、
`updateManager(manager)`が必要じゃないですかね？

2023-02-06 07:29 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
>  const handleEvent = async (client: Client, event: WebhookEvent) => {
> 「改めてこういう形を提案します。」と対になる部分です。


`handleEvent`はPromiseを返す縛りをつけましょう。
`const handleEvent = async (client: Client, event: WebhookEvent): Promise<Message[] | void> => {`

2023-02-15 12:00 UTC, Nekodigi commented on src/handler/manager_line/manager_line.ts
> +}
リアクション部分はこちらです。

2023-02-15 12:00 UTC, Nekodigi commented on src/types/managers.d.ts
> +type ManagerStatus = '名前入力' | ''
マネージャーのステータスは、他のメッセージが混ざる可能性がないのでunion型で定義しています。
createdAtはTimestamp型を使いましたが、Date型よりこちらが良いでしょうか？

2023-02-15 12:00 UTC, Nekodigi commented on nodemon.json
> +}
以前のpull requestで出しているts-nodeとホットリロード対応のコミットがこちらにも入っています。
更新内容が重複していますが、ブランチ管理の仕方を改善した方が良いでしょうか？

2023-02-15 12:00 UTC, Nekodigi commented on src/lib/line/template.ts
> +}
確認メッセージは、altとtextを変えたうえで再利用する可能性があるので、lib/lineへと分離しました。

2023-02-15 12:00 UTC, Nekodigi commented on src/handler/manager_line/manager_line.ts
> +    )
events[0]しか受け取らない場合は、画像を複数枚同時に送るのは避けてもらって１枚ずつ送ってもらう感じですよね。
Promise.allはとりあえず残して、handleEventのエラーを補足する認識で合っていますか？

2023-02-15 12:00 UTC, Nekodigi commented on src/handler/manager_line/manager_line.ts
> +  updateManager(manager)
なるべく1回の応答にまとめたほうが良いということですね。
最上位でcatchするのは、上で言っていたPromise.allのエラーcatch部分でしょうか。
普段やったことがない実装も多いですが、頑張ってみます。
なお、既にテスト週間に入っているので、時間が取れたタイミングで少しづつ修正を加えます。

2023-02-15 12:00 UTC, Nekodigi commented on src/handler/manager_line/manager_line.ts
> +    if (manager.name === '' || manager.status === '名前入力') return newManager
ステータスはkeyword.yesなどと同様に、オブジェクト型で管理するということでしょうか？
const status = {inputName: "名前入力", none: "初期状態"}
firestoreに保存される文字列は、日本語でよいですか？

2023-02-15 12:00 UTC, Nekodigi commented on src/handler/manager_line/setup.ts
> +} from '@line/bot-sdk'
LinterはPrettierと導入を検討していましたが、少し大変そうだったので断念しました。
また時間がある時に挑戦します。

2023-02-15 12:00 UTC, Nekodigi commented on src/lib/firestore/manager.ts
> +  const manager = (await db.collection('managers').doc(lineId).get()).data()
Converter初めて知りました。早速実装してみます。

2023-02-15 12:00 UTC, Nekodigi commented on src/handler/manager_line/manager_line.ts
> +      manager.enable = true
以前このような書き方を教えていただきましたが、awaitを使った書き方でも問題ないですか？
```javascript
return updateManager(manager).then(() => {
  return [decideName(event, manager)]
})
```
awaitを使った場合
```javascript
await updateManager(manager);
return [decideName(event, manager)]
```

2023-02-15 12:00 UTC, Nekodigi commented on src/handler/manager_line/manager_line.ts
>  const handleEvent = async (client: Client, event: WebhookEvent) => {
戻り値は、基本的に全て型指定した方が良いでしょうか？
handle()等の戻り値の型が複雑になる場合や、returnの値によって戻り値の型が暗示的に決まる場合は省いても大丈夫でしょうか？

2023-02-15 12:00 UTC, Nekodigi commented on src/handler/manager_line/setup.ts
> +}
分かりました。
validationが必要ない場合も、特定の情報しか必要としない場合はそれだけを渡す方が良いですか？

2023-02-15 12:00 UTC, Nekodigi commented on src/consts/phrase.ts
> +}
使用頻度が多いフレーズをphrase.tsで定義しました。

2023-02-15 12:00 UTC, Nekodigi commented on src/handler/manager_line/manager_line.ts
> +        }
replyできるメッセージの種類は限られているので、先に判定をしています。

2023-02-16 01:20 UTC, tetsuyanh commented on src/handler/manager_line/setup.ts
> +}
はい。ここはプリミティブなメッセージ整形に止めて、名前をハメたい時は、stringを渡すようにしましょう。
修正コードもそうなっていますね。

2023-02-16 01:32 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
>  const handleEvent = async (client: Client, event: WebhookEvent) => {
@Nekodigi 
関数定義の返り値は徹底したいです。

> 戻り値の型が複雑になる場合

主に返したいもの＋undefinedやvoidのケースまでに収めていこうかと。
`Promise<Hoge[] | undefined | null>`
`Promise<Hoge[] | void>`
もし、ここに型が列挙して増えるようなら、関数自体を分割/層にすべきかなと思います。

> returnの値によって戻り値の型が暗示的に決まる

Wrapしてるだけのやつとかですかね。これも明示していきましょう。
```
const Func = (value number): Fuga[] => {
  return child.subFunc(value);
}
```

2023-02-16 01:38 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +        }
@Nekodigi 
逆に、応答できない方を除外するのはどうでしょう？
私は`unfollow`がreplyToken持ってないのは知っていて、他もありますかね？
ホワイトリスト／ブラックリスト、いずれか少ない方であればOKです。

2023-02-16 01:41 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +        }
細かい部分で、あとですぐ変更できるので許容して、PRをApproveしますね。

2023-02-16 01:41 UTC, tetsuyanh approved these changes

2023-02-17 03:46 UTC, merged