jest init
foodbank-ymg/thanks-web-backend pull request #14
Opened 2023-02-18 05:43 UTC by Nekodigi

簡易的にJestを初期化し、Firestoreのドキュメント作成削除のテストを作成しました。
close #13

2023-02-18 09:14 UTC, tetsuyanh requested changes
@Nekodigi 
早速ありがとう。。
依頼時に説明してなくてほんとに申し訳ないのだけど、
外部サービスの品質担保は外部サービスに任せたくて、
かつ、テスト実行時にFirebaseの認証まで必要になるのは結構辛いのです。
（GithubActionsのCIなどにもAdmin権限を渡さないといけなくなる）

`setup.ts `のテストとかどうでしょうか？（テキスト整形の確認）

ゆくゆくは、コアとなるハンドラーの手順をテストします。
で、その中でもFireStoreへはアクセスせずMockを挿入する予定です。

2023-02-20 01:32 UTC, Nekodigi commented
確かに、テストは認証が必要なものを避けて、簡易に試せる方がいいですね。
Secretが必要となるLINEの送受信のテストも必要ないですよね。
setup.tsのテストは、引数を受け取らず定型を返すものは省き、一部のみをテストする形で大丈夫でしょうか？

2023-02-22 01:19 UTC, tetsuyanh commented
> Secretが必要となるLINEの送受信のテストも必要ないですよね。

はい。基本外部はモックを立てて、我々のロジックのテストに注力します。

> テストが必要になる基準がわかると助かります！

テストファイルを設けたファイル（上記の我々のロジック）は基本すべてやりましょう。
「引数を受け取らず定型を返すもの」はごく僅かになるはずで、これを意味ないとみなさず、
大半である「コードを変えたらテストも変える」という厳密（より安全）な方に倒しましょう。

2023-02-23 11:01 UTC, Nekodigi commented
定型も含めsetup.tsのすべての関数に対してテストを設定しました。

2023-02-27 00:19 UTC, tetsuyanh approved these changes
🆗 
お疲れ様でした！

2023-02-27 00:19 UTC, tetsuyanh commented
@Nekodigi マージしてください。

2023-03-15 08:16 UTC, merged