Recipientコードの実装。
foodbank-ymg/thanks-web-backend pull request #16
Opened 2023-03-28 04:33 UTC by Nekodigi

Recipient側のコードを実装し、動作確認とテストコードの実装を行いました。
schemeに従い、受給者個人はrecipientMemberという名前で実装しましたが、スコープの狭い変数はrecipientと省略しています。
Managerとの共通部分は共有して、冗長にならないようにしました。
以前の実装にならって拡張しただけなので、改善が必要な個所があればご指摘お願いいたします。
4/4まで東京/名古屋に行くため、修正が必要な場合はそれ以降になりますが、ご了承ください。

2023-04-03 04:50 UTC, tetsuyanh requested changes
@Nekodigi レビュー指摘入れました。

大きなところで、スキーマの名義を変えました。
受給団体を「recipientGroup」、受給者を「recipient」と変更。
変更よろしくお願いします！
https://github.com/foodbank-ymg/thanks-web-backend/wiki/Schema

2023-04-03 04:50 UTC, tetsuyanh commented on src/consts/constants.ts
> +export type statusType = (typeof status)[keyof typeof status]
管理者と受給者はステータスが違ってくる＆厳密に分けたいために、型を2つに分けましょう。

```
export const managerStatus = {}
export type managerStatusType = ...

export const recipientStatus = {}
export type recipientStatusType = ...
```

実際に使う際の変数名は、`status`という変数名にしてもOKです。
（管理者と受給者のコードは混じらないはずなので）

2023-04-03 04:50 UTC, tetsuyanh commented on src/handler/common/setup.test.ts
>      text: '友だち追加ありがとうございます。\nこのアカウントでは、文章や画像をチャット送っていただくだけで記事投稿が出来ます。',
setupの共通化は厳しくないでしょうか。
管理者と受給者は立場（役割）が明確違うため、メッセージの細かい部分までそれぞれに適した言い回しをする必要があります。
このメッセージも管理者にとって、「記事投稿ができます」は明らかに間違っています。

システムの都合（しかも今回は強引な共通化）がユーザー体験に悪い影響を出してしまう設計は、よくありません。
あくまでユーザー体験を最優先して、その上でシステムの合理化を目指していきましょう。

2023-04-03 04:50 UTC, tetsuyanh commented on src/handler/recipient_line/recipient_line.ts
> +  const recipient = recipient_ // to make manager constant
ここって、constに置き換える意義が薄いですがどうですかね？
取得（なければ生成）した後に、後述で再代入するリスクはあまりないかなと。

最初のlet宣言から`recipient`にするのどうでしょうか？

2023-04-03 04:50 UTC, tetsuyanh commented on src/consts/constants.ts
> +  inputRecipientId: '団体ID入力',
JSの定数は大文字スネークケースなので、変更お願いします。
```
NONE: '初期状態',
IDLE:  ...
INPUT_NAME:  ...
INPUT_RECIPIENT_ID: ...
```

2023-04-03 04:50 UTC, tetsuyanh commented on src/lib/firestore/recipientMember.ts
> +export const getRecipientByLineId = async (lineId: string) => {
この関数はI/O接点なので、厳密に`getRecipientMemberByLineId`にしたいです。
別ファイルに同名の関数もあるし、生成は`createRecipientMember`にしてるし。

これを使うところは許容できる認識です。
`const recipient = getRecipientMemberByLineId(...)`

2023-04-03 04:50 UTC, tetsuyanh commented on src/handler/recipient_line/recipient_line.ts
> +      return [tellWelcome(), askName()]
ここは名前が空だったら、という条件にして、該当する場合（初回フォロー、再フォローどちらでも）は、
「名前を聞く」ステータスに更新して、名前を聞く、というのが正しいはずです。

```
if (recipient.name === '') {
      recipient.status = status.inputName
      await updateRecipientMember(recipient)
      return [tellWelcome(), askName()]
```

そして、create時のステータスはNONEにしましょう。

2023-04-03 04:50 UTC, tetsuyanh commented on src/handler/recipient_line/recipient_line.ts
> +      return [tellWelcome(), askRecipientId()]
ここも同様です、フォロー時の状態（初回であろうと復帰であろうと）で判断して、
再開時のステータスを決めるべきです。
```
else if (recipient.recipientId === '') {
      recipient.status = status.inputRecipientId
      await updateRecipientMember(recipient)
      return [tellWelcome(), askRecipientId()]
```

2023-04-03 04:50 UTC, tetsuyanh commented on src/handler/recipient_line/recipient_line.ts
> +            return [confirmName(recipient.name)]
名前確認さえも1つの新しいステータス`COFIRM_NAME`で切り分けてもいいかもしれません。
このcaseの中で2つの状態が混じってしまっているので。

2023-04-03 04:50 UTC, tetsuyanh commented on src/handler/recipient_line/recipient_line.ts
> +            }
名前確定→受給ID入力という順の流れなので、
ここで受給IDがあるケース（elseの方）は想定しなくて良い気がします。if文も不要。

2023-04-03 04:50 UTC, tetsuyanh commented on src/handler/recipient_line/recipient_line.ts
> +        const recipientGroup = await getRecipientById(event.message.text)
受給者の方がメインユーザーなので、
受給者＝recipient、受給団体＝recipientGroupというスキーマ定義の方がいいですね。

Wikiを上記のように更新します。
すいませんが、追従をお願いします。

2023-04-05 02:04 UTC, Nekodigi commented on src/lib/firestore/recipientMember.ts
> +export const getRecipientByLineId = async (lineId: string) => {
getRecipientGroupByLineIdにして重複を避ける方向で進めようと思うのですが、どうでしょうか。
スキーマも変更しているので。

2023-04-05 05:18 UTC, Nekodigi commented on src/handler/common/setup.test.ts
>      text: '友だち追加ありがとうございます。\nこのアカウントでは、文章や画像をチャット送っていただくだけで記事投稿が出来ます。',
setupはそれぞれ分けて実装します。
manager側の役割をうまく把握していないのですが、投稿は行わず、記事管理のみを行うといった感じでしょうか？
詳細な役割を教えていただけると、正しいメッセージを書くのに助かります。

2023-04-05 08:31 UTC, tetsuyanh commented on src/handler/common/setup.test.ts
>      text: '友だち追加ありがとうございます。\nこのアカウントでは、文章や画像をチャット送っていただくだけで記事投稿が出来ます。',
マインドマップツールで、左下の島の「ユースケース」をおおまかな仕様と考えています。
https://drive.google.com/drive/folders/1BBSS52KnX9SrS4iU1CoMOjRu1L7LWz00

manager（フードバンク山口）は記事の監督を行います。

2023-04-05 08:38 UTC, tetsuyanh commented on src/lib/firestore/recipientMember.ts
> +export const getRecipientByLineId = async (lineId: string) => {
団体の方に`Group`を付与して識別するようにしたので、
すべて、受給者＝`recipient`にして大丈夫です。

2023-04-05 11:26 UTC, Nekodigi commented on src/lib/firestore/recipientMember.ts
> +export const getRecipientByLineId = async (lineId: string) => {
上部のimport文は不要なのですが、これがなければis not module.エラーが出てしまいます。
対処法を知っていれば教えていただけないでしょうか？
```JavaScript
import { recipientStatusType } from '../consts/constants'

type RecipientGroup = {
  id: string
  name: string
  enable: boolean
  createdAt: Date
}
```

2023-04-05 12:00 UTC, tetsuyanh commented on src/handler/common/setup.test.ts
>      text: '友だち追加ありがとうございます。\nこのアカウントでは、文章や画像をチャット送っていただくだけで記事投稿が出来ます。',
@Nekodigi ↑
メッセージは大まかに合ってればよしとして、実際、触ってもらってから細かな表現は修正していきしょう。

2023-04-05 12:06 UTC, tetsuyanh commented on src/lib/firestore/recipientMember.ts
> +export const getRecipientByLineId = async (lineId: string) => {
うーん、私の方はエラー出ないですねー。

2023-04-05 12:07 UTC, Nekodigi commented on src/lib/firestore/recipientMember.ts
> +export const getRecipientByLineId = async (lineId: string) => {
tsconfig.jsonがあやしいかなと思っているのですが、良く分からないです。
エラーが出続けるので、原因が分かるまで、import文は残しておきます。

2023-04-06 01:19 UTC, Nekodigi commented
指摘していただいた部分の修正と、テストコードの追加を行いました。
このコードはまだ暫定ですが、方向性が合っているかの確認をお願いします。

2023-04-06 02:20 UTC, tetsuyanh commented
@Nekodigi 方向性合ってます。このまま実装お願いします。

既知や作業途中かと思いますが、一応気づいた点を伝えておきます。

- `yarn add -D @babel/preset-env`しないと、`yarn test`が通らない

- statusは必ず定数を使う
  - `getRecipient('', '', '初期状態'))` -> `getRecipient('', '', recipientStatus.NONE))`

- テストで何度も渡すeventも`getEvent(...)`を用意して短文で済ませるのが良さそう

2023-04-06 03:32 UTC, Nekodigi commented
webhook event のevent.typeの型が分からないのですが、Visual Studio Codeでどうすれば確認できるのでしょうか？

2023-04-06 08:13 UTC, Nekodigi commented
指摘していただいた部分を一通り修正し、動作を確認しました。
レビューよろしくお願いします。

2023-04-09 14:19 UTC, tetsuyanh approved these changes
@Nekodigi お疲れ様でした。
細かい指摘1点入れましたが、次回のPR作業時で大丈夫です。
Approveします。マージちゃってください。
今後は自動でリリースされますね。（もう手動でリリースしちゃってるかもですが）

2023-04-09 14:19 UTC, tetsuyanh commented on src/consts/constants.ts
> +  INPUT_RECIPIENT_ID: '団体ID入力',
運営者側はこのステータスありません。

2023-04-09 14:21 UTC, merged

2023-04-09 14:26 UTC, Nekodigi commented
このPRはmainにマージされる設定になってるんですが、developにマージされるようにしないといけないですよね…
mainへのマージをrevertして、developに向かうPRを別で立てたほうが良いでしょうか？

2023-04-10 00:25 UTC, tetsuyanh commented
@Nekodigi そうでした。。向き先をdevelopにしようとして忘れてた。
これお願いします。

> mainへのマージをrevertして、developに向かうPR