Post
foodbank-ymg/thanks-web-backend pull request #20
Opened 2023-04-18 01:21 UTC by Nekodigi

記事作成の流れを実装しました。
画像追加を3件まで行えるようにして、記事削除した際は同時に消えるようにしています。

＜変更点＞
画像の保存パスについて。記事単位のフォルダ作成しました。
posts/[id]/images/
画像追加はtransactionを使っていて,更新もそこで完結します。
＜疑問点＞
firebase storageでフォルダごと削除したのですが、参考例はありますか？現在は一つひとつ消しています。
作成中記事は、新規で追加したWAITING_REVIEW statusで判断しています。ただ、記事作成後のステータスが増える予定があるなら。もう一つediting:bool型を追加した良いかなと思っています。

2023-04-18 02:31 UTC, Nekodigi commented
一応動作確認はしていますが、改善できる点はいくつかあると思うので、確認よろしくお願いします。
post_line,postのテストコードを記入したので、レビューと他にテストが必要な場所があれば指示をお願いします。
加えて、予想されるJsonを手動入力するのは冗長なので、ConfirmTemplate等の単体テストを追加して、他のテスト内でそれらの関数を使うように書き換えようと思います。

2023-04-22 15:15 UTC, tetsuyanh requested changes
@Nekodigi 
指摘入れました。

あらかた修正できたら、マージまでして、開発環境で触ってみたいです。
そこで不備などあれば、またissue積んで別PRでやりましょう。

2023-04-22 15:15 UTC, tetsuyanh commented on src/config/config.ts
> +    require('dotenv').config()
すいません、この1つ上のif文に開発サイトのdevelop環境も考慮してください。
本番環境でもなく開発環境でもない、ならローカル環境でdotenvを読む形で。

2023-04-22 15:15 UTC, tetsuyanh commented on src/consts/keyword.ts
> +  CONFIRM: '決定',
「CONFIRM」だと「確認」なので、「DECIDE」はどうでしょう？

2023-04-22 15:15 UTC, tetsuyanh commented on src/handler/recipient_line/recipient_line.ts
> +        let post = await getWorkingPostByRecipientId(recipient.id)
handler冒頭のrecipientを取得した後に、
ステータスがINPUT_POSTなら、postもそこで取得しちゃいましょう。
postが取得できなければ、その時点でデータ不整合としてエラーを返せます。（不整合の際の対応はTODOで・・）

この行では既に確かなpostが取得できていることになります。

2023-04-22 15:15 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +  deletePostData(post)
ここはFirestoreの操作に特化したファイル（libですが、それぞれ異なるinfrastructure）です。
同列のストレージに跨った操作をするのは悪手です。

上位（handler層）でこの順で操作しましょう。
・DB削除
・ストレージ削除
もし後者でエラーが発生しても、ストレージにゴミデータが残るだけで運営上あまり重要でない。

逆の順（ストレージ削除が成功してDB削除が失敗）だと、画像がない投稿が生まれてしまい良くないからです。

2023-04-22 15:15 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +    id: `r-${makeId(4)}`,
prefixが`r-`なのはrecipientです。
wikiでは、このように定義していました。{受給団体ID}-{タイムスタンプ}
`rg-XXXX-YYmmdd-HHMMSS`

2023-04-22 15:15 UTC, tetsuyanh commented on src/lib/storage/post.ts
> +export const uploadResizedImage = async (image: Buffer, size: number, post: Post) => {
リサイズしていませんが、この関数名なのでしょうか？引数のsizeも使っていませんし。

リサイズ操作をするなら、この関数を呼ぶ前段でやりたいです。

2023-04-22 15:15 UTC, tetsuyanh commented on src/lib/line/template.ts
> +      imageUrl: 'https://example.com/sushi.png',
アイコンがあると、サービスの親しみや心地よさが上がりますよね。
できればラベルと一致するようなアイコンにしたいですが、
そのためには引数でアイコンも伝えないといけないですよね。

一旦、アイコン無しでいい気がしました。

2023-04-22 15:15 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +  await db.runTransaction(async (transaction) => {
これトランザクションの意味あるのですっけ？
すいません、私が読み解けてないかもですが。。

関数を呼ぶ前に、postに対して`post_.images.push(image)`してやって、
結局、`updatePost`してやればいいのかなと思いました。

2023-04-22 15:15 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +  return post as Post | undefined
このコードの通り、複数取得しても、上書きして一件しか返さないでOKです。
基本、受給者は1つしか作業Postをつくれないはずなので。

2023-04-22 15:15 UTC, tetsuyanh commented on src/handler/recipient_line/recipient_line.ts
> +            }
ユーザーIDで引くのであれば、`getPostByUserId`という名前にするべきですが、
そもそもユーザーが何度も投稿するので、この関数はそもそも不要なのではと考えています。

ここでは、getWorkingPostByRecipientIdを使って、古い記事が残っていればそれを継続。
見つからない場合に、createPostして新しい作業Postを作るのはどうでしょうか？

さらに、createした次の行で`postStatus.INPUT_SUBJECT`ステータスにするのであれば、
そもそもcreate時の初期値が`postStatus.INPUT_SUBJECT`で良いと思います。
（Postにおいては、`NONE: '初期状態'`は不要？）

2023-04-22 15:15 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +      .where('status', '!=', postStatus.WAITING_REVIEW)
いずれ、後続のステータスが増えた場合は、
`isRecipientWorking`というbooleanの要素を足して、それで判定することになりそうです。

2023-04-22 15:15 UTC, tetsuyanh commented on src/handler/recipient_line/recipient_line.ts
> +        let image = await downloadImageById(event.message.id)
このファイル内で、既に`client.replyMessage`という形でclientを使っているので、

downloadImageByIdは`/lib/image.ts`で外出しせずに、ここで直接書いてもいい気がしています。
handleEven(client, event)のように引数でclientをもらって。

なので、clientもグローバルにする必要はなくなります。
そもそもhandlerの変数をlibで使う方向がよくありません。
libは使われる側に徹するべきです。

2023-04-22 15:17 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +      .where('status', '!=', postStatus.WAITING_REVIEW)
コメントで同じことを言ってましたね。
```
作成中記事は、新規で追加したWAITING_REVIEW statusで判断しています。ただ、記事作成後のステータスが増える予定があるなら。もう一つediting:bool型を追加した良いかなと思っています。
```

もう、`isRecipientWorking`の足してもいいですよ。
適切なタイミングで初期化と更新を入れてください。

2023-04-22 15:18 UTC, tetsuyanh commented
> firebase storageでフォルダごと削除したいのですが、参考例はありますか？現在は一つひとつ消しています。

これは現状でも問題なく、優先度低いので調査は保留にさせてください。

2023-04-24 08:06 UTC, Nekodigi commented on src/lib/firestore/post.ts
> +  await db.runTransaction(async (transaction) => {
画像を一つ一つ送ってもらった場合はいいのですが、仮に複数同時に画像が送信された場合、メッセージの間隔が短すぎて画像が正常に追加されない事があるためです。ここで正常に追加できないと、記事削除の場合に、追跡できていない画像が消えずに残ったりするので…
もちろん、動作に問題がないのであればTransactionにする必要はないです。

2023-04-28 03:07 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +  await db.runTransaction(async (transaction) => {
@Nekodigi ここは仕様を制約を設けて（シンプルにして）、1つずつ受け入れるようにしましょう。
サービス全体を通して、events[0]しか対応しない。

2023-04-28 03:37 UTC, tetsuyanh requested changes
@Nekodigi 指摘足しました。コメントに対する返答がないとこ、回答ください。

2023-04-28 03:37 UTC, tetsuyanh commented on src/handler/recipient_line/post_line.test.ts
> +    id: 'r-0001',
一応、postのID規則にしておきましょう。

2023-04-28 03:37 UTC, tetsuyanh commented on src/handler/recipient_line/post_line.ts
> +          await deletePost(post)
画像の削除だけは、許容してよい（＝正常系）と考えています。
具体的には、画像が3枚あって1枚削除に失敗した時の中途半端な状態を考慮したくない、です。

なので、ゴミが残るのは許容して、ログだけ履いて、正常系（対ユーザーではフローが進む）を維持したいです。
ここでエラー対応して、上位のエラー返答にはしない。
```
await updateRecipient(recipient)
await deletePost(post)
deletePostData(post).catch((err) => {
  console.error(...)
})
```

2023-04-28 03:37 UTC, tetsuyanh commented on src/handler/recipient_line/recipient_line.ts
> +              await updatePost(post)
createPostの中で保存（updatePostを内包）は済んでます。132行目は不要です。

2023-04-28 03:37 UTC, tetsuyanh commented on src/handler/recipient_line/post_line.ts
> +          post.isRecipientWorking = false
レビュー中は`isRecipientWorking`はtrueのままかなと思いました。
レビュー中に次の投稿を作らせないためです。

manager側が許可して、その際にtrueにすべきかと。

2023-04-29 12:43 UTC, Nekodigi commented on src/handler/recipient_line/post_line.ts
> +          post.isRecipientWorking = false
レビュー中には他の記事は投稿できないほうが良いのですね。分かりました。

2023-04-29 13:59 UTC, Nekodigi commented
レビューに対する修正を加えました。
events[0]にしか対応しないということで、handleの実装を少し変更しました。

2023-04-30 06:29 UTC, tetsuyanh commented on src/lib/storage/post.ts
> +export const uploadResizedImage = async (image: Buffer, size: number, post: Post) => {
@Nekodigi 
折りたたまれていて気づかないかもしれませんが、ここの回答まってます。

2023-04-30 06:30 UTC, tetsuyanh commented on src/lib/line/template.ts
> +      imageUrl: 'https://example.com/sushi.png',
@Nekodigi 
ここの回答もまってます。

2023-04-30 07:11 UTC, tetsuyanh requested changes
@Nekodigi 
1つ指摘追加しました。
まだ回答もらってないやつも残ってます。

2023-04-30 07:11 UTC, tetsuyanh commented on src/handler/manager_line/manager_line.ts
> +    const event: WebhookEvent = req.body.events[0]
この行の前で、eventsの空チェックして、早期リターンしてください。（recipientの方も）
LINEDeveloperにURLをセットして「検証」ボタン（疎通確認）した時にメッセージが空だった気がします。
```
if (!req.body.events || req.body.events.length === 0) {
  return res.status(200)
}
```

2023-04-30 11:52 UTC, Nekodigi commented on src/lib/storage/post.ts
> +export const uploadResizedImage = async (image: Buffer, size: number, post: Post) => {
畳まれていたのでresolveされたものと勘違いしていました。
resize処理を別で記述して、名前と引数も変更しました。

2023-04-30 12:01 UTC, Nekodigi commented on src/lib/line/template.ts
> +      imageUrl: 'https://example.com/sushi.png',
サンプルのコードを直し忘れていました。アイコンいったん消しておきます。

2023-05-01 07:23 UTC, tetsuyanh approved these changes

2023-05-01 07:23 UTC, tetsuyanh commented
@Nekodigi 🙆‍♂️ です。お疲れ様でした！
マージしちゃってください。その後、ローカルでdevelopをplして、そこから新しいissueに取り組んでください。

2023-05-02 03:04 UTC, merged