Feature/review post
foodbank-ymg/thanks-web-backend pull request #24
Opened 2023-05-08 14:34 UTC by Nekodigi

レビューワークフローを実装し、LINEでの動作を確認しました。

close #21 

投稿最終確認時とレビュー時のプレビュー表示
投稿承認時のPush通知
画像は3枚まで表示できる仕様にしていますが、投稿時にMAX_IMAGEで1枚までに制限しています。

2023-05-14 12:59 UTC, tetsuyanh requested changes
@Nekodigi お待たせしました。修正お願いします。

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/recipient_handler/setup.ts
> +}
この関数は、`setup.ts`ではなく`post.ts`にあるべきではないでしょうか？

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/recipient_handler/setup.test.ts
> +  )
関数の指摘同様、`post.test.ts`ファイルにあった方がいいです。

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/recipient_handler/post.ts
> +  return TextTemplate(`次に、画像を一枚づつ送信してください。3枚まで追加できます。`)
他のファイルでも定義してますが、ここも`IMAGE_MAX = 1`を定義して使いましょう。
`...${IMAGE_MAX}まで追加できます。`

頻繁に変わっていくのであれば環境変数としたいですが、一旦、定数定義で。

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/recipient_handler/post.ts
> +    `記事の送信が完了しました。事務局が投稿内容を承認後、翌月の初めに表示されるようになります。`,
月次ページとは別に、直近何十件の一覧を出すページの要件が決まっています。
投稿完了後（承認も）に、すぐサイトに反映される体験がモチベーションになるという観点で。

なので、この一文を変更してください。
`翌月の初めに表示されるようになります。`→`サイトに反映されます。`

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/recipient_handler/post_handler.ts
>            await updateRecipient(recipient)
レビュー中は、受給者はまだ`INPUT_POST`ステータスに留めておいた方がいいと思いました。

`IDLE`に戻すと、無用に他の操作を開始させてしまう恐れがあります。

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/recipient_handler/post_handler.ts
> +          )
Pushも非同期にしてawaitで待つ方がよいと思いました。

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/recipient_handler/post.ts
> +export const AskPostReview = (name: string, postId: string) => {
先頭小文字にしましょう。
自由記述はaskできたので、二者択一はconfirmで統一していきましょうか。
あと、承認するか否かはすべてapproveの動詞で揃えていきましょうか。
`confirmToApprovePost`という感じはどうでしょう？

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/recipient_handler/post.ts
> +export const PostPreview = (subject: string, body: string, images: string[]) => {
小文字で動詞を先に。
`previewPost`

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/recipient_handler/post.ts
> +  }
当面、画像複数は対応しません。デザインの変更や考慮が大きいので。
なので、コメントアウト、もしくは削除でいいくらいです。
（せっかく検証と実装してもらったのにすいません。。）

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/manager_handler/manager_handler.ts
> +  let post = await GetPostById(data.target)
const使ってください。

recipientの更新も必要なので、先んじてここで取得しておきましょう。
`const recipient = await GetRecipientById(post.recipientId)`

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/manager_handler/manager_handler.ts
> +      await updatePost(post)
受給者（投稿者）のステータスをIDLEに戻す更新が必要です。
postの更新に続き、ここでやりましょう。

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/manager_handler/post.ts
> +export const RejectedPostForRecipient = (name: string, subject: string) => {
関数は小文字始まりで。
引数nameは使ってないので削除。

他で指摘したように、
`来月の初めに表示される様になります。` →`数分後にサイトに反映されます。`

2023-05-14 12:59 UTC, tetsuyanh commented on src/handler/manager_handler/post.ts
> +export const RejectedPostForManager = (name: string, subject: string) => {
関数は小文字始まりで。

2023-05-14 12:59 UTC, tetsuyanh commented on src/lib/storage/storage.ts
> +}
このファイルは汎用的なストレージ操作であって、
サービス提供向けのURLパス整形は別にしたいところですが、
utilsなどに配置するのも違うので、一旦このままでいきます。

2023-05-14 12:59 UTC, tetsuyanh requested changes
@Nekodigi お待たせしました。修正お願いします。

2023-05-14 13:03 UTC, tetsuyanh commented
@Nekodigi 
 .githubのymlを以下のようにして、
この作業ブランチがPushされる（上津原くんの作業の）たびに、
開発環境に自動デプロイするようにして、受給者側と管理者側で動作確認までしてください。
動かなければその対応もしてください。

```
on:
  push:
    branches:
      - develop
      - feature/review-post
```

2023-05-14 13:05 UTC, tetsuyanh commented
あ、もしかして、いま開発環境が全く反応しないのは、
LINEのWebhookを、上津原くんの個人環境に向けて検証してたからかな。。

2023-05-17 05:43 UTC, Nekodigi commented
> あ、もしかして、いま開発環境が全く反応しないのは、 LINEのWebhookを、上津原くんの個人環境に向けて検証してたからかな。。

開発中はローカルのURLをセットしています。
自動デプロイを後で検証してみますね。

2023-05-17 05:44 UTC, Nekodigi commented on src/handler/manager_handler/post.ts
> +export const RejectedPostForManager = (name: string, subject: string) => {
外部からアクセスされる関数は大文字で始めた方が良いかと思って一部大文字に移行していましたが、また小文字に戻しておきます。

2023-05-17 06:15 UTC, Nekodigi commented on src/handler/recipient_handler/post.ts
> +  }
@tetsuyanh 
画像がないケースは考えられますか？

2023-05-17 07:01 UTC, Nekodigi commented
問題を修正して、動作確認を行いました。webhookのURLもcloud runのものになっています。
レビューよろしくお願いします。

2023-05-17 12:30 UTC, tetsuyanh commented on src/handler/recipient_handler/post.ts
> +  }
@Nekodigi いえ。必須にしましょう。

2023-05-17 12:48 UTC, tetsuyanh approved these changes
何点か返信と指摘残ってますがApproveしておきまうs。
修正コミット後マージしてください。

2023-05-17 12:48 UTC, tetsuyanh commented on src/handler/recipient_handler/post_handler.ts
>            await updateRecipient(recipient)
元々、ステータスは「INPUT_POST」なので、更新自体不要かと思います。

2023-05-19 13:16 UTC, tetsuyanh commented
@Nekodigi 
1点追加です。
管理側が、許可/不許可を押すたびに、毎回通知してしまうので、
許可/不許可された投稿に対して押された場合は無視（上位に返す返答メッセージを空配列にして何もさせない）してください。

2023-05-22 23:39 UTC, merged