Feature/delete post
foodbank-ymg/thanks-web-backend pull request #29
Opened 2023-06-13 02:56 UTC by Nekodigi

recipientのバグ修正と、managerの削除機能実装を行いました。

close #27

2023-06-16 07:51 UTC, tetsuyanh requested changes
issueでも書いた通り、削除もシートにログとして残したいです。

2023-06-16 07:51 UTC, tetsuyanh commented on src/handler/manager_handler/manager_handler.ts
> +          deletePostData(post).catch((err) => console.error(err))
削除を2回呼んじゃってます。

2023-06-20 02:38 UTC, Nekodigi commented
ログが出るようにしました。

2023-06-21 01:45 UTC, tetsuyanh approved these changes

2023-06-21 01:46 UTC, tetsuyanh commented
@Nekodigi 
お疲れさまでした。Approveしました。マージをお願いします。
（もう1つの方は少しお待ちください・・）

2023-06-21 01:46 UTC, merged