Feature/post update web
foodbank-ymg/thanks-web-backend pull request #35
Opened 2023-07-08 08:20 UTC by Nekodigi

githubのdeployアクションの呼び出しと、deploy後処理を実装しました。
認証はjwtを用いており、Authorization: Bearer [secret]のようにHeaderを設定すると呼び出せます。
close #33

2023-07-09 06:45 UTC, tetsuyanh requested changes
@Nekodigi 
レビューしました。

2023-07-09 06:45 UTC, tetsuyanh commented on src/lib/github/github.ts
> +          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1521.3 Safari/537.36',
すいません、これは外しましょうか。誤りなので。

2023-07-09 06:45 UTC, tetsuyanh commented on src/handler/hook/publish_posts_handler.ts
> +      ])
`recipientId`,`approvedBy`は自分たちの管理用のIDで、LINEのIDではない気がするのですが。
面倒ですが、getで管理している`lineId`を引く必要があるのではないでしょうか？

2023-07-09 06:45 UTC, tetsuyanh commented on src/handler/hook/hook_middleware.ts
> +  }
良い感じです。 👍

2023-07-09 06:46 UTC, Nekodigi commented on src/lib/github/github.ts
> +          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1521.3 Safari/537.36',
User-Agentを設定しないとエラーになるのですが、何を設定したらよいでしょうか？

2023-07-10 01:14 UTC, Nekodigi commented on src/lib/github/github.ts
> +          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1521.3 Safari/537.36',
一旦 githubapiを設定しておきますね。

2023-07-10 03:35 UTC, tetsuyanh approved these changes

2023-07-10 03:35 UTC, tetsuyanh commented
@Nekodigi お疲れ様でした。マージしておきます。

2023-07-10 03:35 UTC, merged