Feature/rejected reason
foodbank-ymg/thanks-web-backend pull request #48
Opened 2023-11-03 14:54 UTC by Nekodigi

rejectの理由を入力できるようにしました。
今のところ、確認処理は含めていません。
close #47

2023-11-12 04:45 UTC, Nekodigi commented
@tetsuyanh 
数点修正しましたが、こちらマージして大丈夫でしょうか？

2023-11-13 05:34 UTC, tetsuyanh requested changes
@Nekodigi 修正お願いします。

2023-11-13 05:34 UTC, tetsuyanh commented on src/handler/manager_handler/manager_handler.ts
> +          post_.rejectedManagerId = manager.id
この更新は不許可ボタンを押した直後にセットしてるので不要ですよね？

2023-11-13 05:34 UTC, tetsuyanh commented on src/lib/firestore/post.ts
> +      .get()
このクエリだと、過去に不許可＆フィードバック済み投稿を拾い続けてしまいますよね。
`isRecipientWorking == true`を条件に足すのはどうでしょうか？
関数名も`getWorkingPostBy...`で。

ある管理者が同時に2つの投稿を不許可の理由を書いてる途中というケースはレアなので
許容しようと思います。

2023-11-13 05:35 UTC, tetsuyanh commented
@Nekodigi レビュー前提のPR運用をしてるのでセルフマージは控えましょう。
ほんとに軽微なやつは許容できますが

2023-11-16 23:21 UTC, tetsuyanh approved these changes

2023-11-16 23:21 UTC, merged